clusters:
  sno-<name>:
    applicationNamespace: openshift-operators
    namespace: ''
    destination: 'https://kubernetes.default.svc'
    project: default
    code:
      repo: https://github.com/romerobu/helm-infra-gitops-workshop.git
      path: .
      target: sno-<name>