# Default values for gitops setup

global:
  render: true
  argocd:
    enabled: true
    controller: openshift-operators
  operators: 
    enabled: true
  rbac: 
    enabled: true 
  namespace: openshift-operators
  domain: <domain>
  sno:
    15: 
      token: sha256~3PqApV-yySsHUMVf_8ztW4YAYTPXlvCDjTNAorZHhrg      