apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: pro
  namespace: openshift-operators
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: 'pro'
      server: '*'
  sourceRepos:
    - '*'