apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: openshift-operators
  name: app01-dev
spec:
  destination:
    name: ''
    namespace: dev
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/acidonper/jump-app-gitops.git'
    targetRevision: 'feature/jump-app-dev'
    helm:
      valueFiles:
        - values-quay.yaml
  project: dev
  syncPolicy:
    automated:
      prune: false
      selfHeal: false  